language: android
dist: trusty
jdk:
  - oraclejdk11
android:
  components:
    - android-30
    - build-tools-30.0.3
    - platform-tools-30.0.5
    - tools
    - extra-android-m2repository
before_install:
  - chmod +x gradlew
