language: android
android:
 components:
 - build-tools-30.0.3
 - android-30
 - android-22
 - add-on
 - extra
 - platform-tools
 - tools
 - extra-google-m2repository
 - extra-android-m2repository
 - sys-img-armeabi-v7a-android-22
before_install:
 - yes | sdkmanager "platforms;android-30"
 - chmod +x gradlew
