language: android
dist: trusty
jdk: oraclejdk11
android:
 components:
  - android-30
  - build-tools-30.0.3
  - platform-tools-30.0.5
  - tools
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-30"
script: ./gradlew -Dorg.gradle.jvmargs=-Xmx1536m assembleDebug lintDebug
