language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
    - android-30
    - build-tools-30.0.3
    - platform-tools-30.0.5
    - tools
  licenses:
    - '.+'
sudo: required
install: true
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
