language: android
jdk: oraclejdk11
dist: trusty
env:
  - JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions'
android:
  licenses:
    - '.+'
 
  components:
    - tools
    - build-tools-30.0.3
    - android-30
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
 
before_install:
  - chmod +x gradlew
