language: android
dist: trusty
jdk:
  - oraclejdk11
android:
  components:
    - android-30
    - build-tools-30.0.3
    - platform-tools-30.0.5
    - tools
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - chmod +x gradlew
